### ISSUE TITLE
Indiquer la version minimale requise de NodeJS

### ISSUE THREAD

**Issue by blex41** [Ouest-France/platform-app-sipaui#107]
Après m'être retrouvé face à ce problème, je pense qu'il serait bien d'indiquer quelque part qu'il faut au minimum Node v10.10.0 pour pouvoir dév ou builder ce projet. J'étais sur Node v9.11.1, et j'obtenais cette erreur sans trop comprendre pourquoi :
```
TypeError: Cannot read property 'startsWith' of undefined
    at fs.readdirSync.filter.dirent (/home/aleveque/workspace/fun/platform-app-sipaui/gulpfile.js:31:33)
```
Après avoir été voir la doc de NodeJS, j'ai vu que [la classe `fs.Dirent` n'existe que depuis Node v10.10.0](https://nodejs.org/api/fs.html#fs_class_fs_dirent).

**Comment by Derwoed** [comment]
Demande traitée en 2.0.1
